[tool.poetry]
name = "cdcstream"
version = "0.1.2"
description = "Implementation of Ienco's algorithm CDCStream"
authors = ["Martin Trat <trat@fzi.de>"]

[tool.poetry.dependencies]
packaging = "*"
python = "3.9.*"
numpy = "*"
pandas = "*"
python-javabridge = "*"
python-weka-wrapper3 = ">=0.2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
